;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.Shield",DevComment="")
+GameplayTagList=(Tag="Cooldown.Teleport",DevComment="")
+GameplayTagList=(Tag="Data.CloneBuildUp",DevComment="")
+GameplayTagList=(Tag="Data.CloneCharge",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Effects.Attack.Blocked",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start.L",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start.R",DevComment="")
+GameplayTagList=(Tag="Event.JumpApex",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Death",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Targeting",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger.CloneFollowup",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger.CloneSpawn",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AOEAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Clone.BasicAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Clone.Explode",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Clone.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Clone.TeleportStab",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Block",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Effect.Fade",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Effect.Fade.IN",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Effect.Fade.OUT",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Knockback",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Basic",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Teleport",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOEIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Boss.Projectile.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.Boss",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.Boss",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.Galaxy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TeleportExplosion",DevComment="")
+GameplayTagList=(Tag="State.Active",DevComment="")
+GameplayTagList=(Tag="State.AntiHeal",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Exit",DevComment="")
+GameplayTagList=(Tag="State.Healing",DevComment="")
+GameplayTagList=(Tag="State.Invulnerable",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Team.Clone",DevComment="")
+GameplayTagList=(Tag="Team.Enemy",DevComment="")
+GameplayTagList=(Tag="Team.Player",DevComment="")

